# .streamlit/secrets.toml
[upstox]
api_key = "f4d5e125-32c8-472e-b72a-f53b8fbaae7a"
api_secret = "bmmz804gjj"
redirect_uri = "http://localhost"

[telegram]
bot_token = "123456789:ABCdefGHIjklMNOpqrSTUvwxYZ"
chat_id = "123456789"

[scanner]
interval = "5minute"
lookback_bars = 200
min_volume = 500000
top_n = 10
